### ISSUE TITLE
View a package's location on a map

### ISSUE THREAD

**Issue by hackergrrl** [watson/geopkg#2]
This might be creeping outside of the scope of this module, but long/lat coords being hard for humans to read, it'd be nice to invoke e.g.

`$ geopkg show screen-stream`

and have `$BROWSER` show me that npm package's location visually.

Maybe better suited as a new module?

**Comment by watson** [comment]
@noffle You can already write `geopkg open` - this will open the detected location in your default browser. I guess this is what you are after?

**Comment by hackergrrl** [comment]
Very close to that. I meant being able to invoke `geopkg open` on
modules I don't have installed:

```
$ geopkg open some_module_I_dont_have_installed
```

and have it query the `package.json` on npm and show me its location.

**Comment by watson** [comment]
Ahh :) That would be sweet. I've been thinking of ways to use this data, but was more thinking of a personalized map of some sort with all packages published by a specific mom user. But both would be cool. I would think that would be a new module though (as you also mentioned). I'll close this one for now :) I appreciate the feedback
